print("Welcome to the Breaking Bad Computer")
import time
time.sleep(1.25)
name = input("What should we call you hermano? ")
crystal = input("Whats up " + name +", how many crystals do you need?")
print("You need " + crystal + " crystals?! Jesus! Either your trying to put me out of business or your need serious help!")
time.sleep(1)
print("...")
time.sleep(1)
print("...")
time.sleep(1)
print("...")
time.sleep(2)
print("Here are your " +crystal+ " crystals, don't use them all in one place!")
